blog_homepage:
    path:     /{page}
    defaults: { _controller: BlogBundle:Public:index , page: 1}
    requirements:
        page : \d+
article_only:
    path:     /{id}/{slug}
    defaults: { _controller: BlogBundle:Public:only }
    requirements:
        id : \d+
page_categorie:
    path : /Categorie/{id}/{name}
    defaults : { _controller : BlogBundle:Public:categorie}
    requirements :
        id : \d+
page_tag:
   path : /Tag/{name}
   defaults : { _controller: BlogBundle:Public:tag}

